# Generated by Django 3.2.8 on 2022-04-17 10:40

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_acceptauthtoken_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_photos')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватарки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_app.models.user_profile_file_path),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='photos',
            field=models.ManyToManyField(to='user_app.Photo'),
        ),
    ]
