# Generated by Django 3.2.8 on 2022-04-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20220417_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография пользователя', 'verbose_name_plural': 'Фотографий пользователей'},
        ),
    ]
