export const GET_FRIEND_REQUEST = "GET_FRIEND_REQUEST";
export const GET_FRIEND_REQUESTS = "GET_FRIEND_REQUESTS";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DELETE_FRIEND_REQUEST = "DELETE_FRIEND_REQUEST";
export const REMOVE_FRIEND_REQUEST_FROM_LIST = "REMOVE_FRIEND_REQUEST_FROM_LIST";
export const GET_ALL_FRIENDS = "GET_ALL_FRIENDS";
export const DELETE_USER_FROM_FRIEND_LIST = "DELETE_USER_FROM_FRIEND_LIST";
