# Generated by Django 3.2.7 on 2021-10-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
