# Generated by Django 3.2.7 on 2021-10-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('soc_api', '0002_delete_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWasUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_used', models.IntegerField(db_column='Использований', default=0)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Время обновления')),
                ('token', models.ForeignKey(db_column='Токен', on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
            options={
                'verbose_name': 'Использований токена',
                'verbose_name_plural': 'Использования токенов',
            },
        ),
    ]
