# Generated by Django 3.2.7 on 2021-10-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('soc_api', '0004_remove_tokenwasused_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwasused',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='tokenwasused',
            name='how_many_used',
            field=models.IntegerField(db_column='was_used', default=0),
        ),
        migrations.AlterField(
            model_name='tokenwasused',
            name='token',
            field=models.ForeignKey(db_column='token', on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
