# Generated by Django 3.2.7 on 2021-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_api', '0005_auto_20211017_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwasused',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tokenwasused',
            name='how_many_used',
            field=models.IntegerField(default=0),
        ),
    ]
