# Generated by Django 3.2.8 on 2022-04-17 10:12

import content_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_group_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(default='', upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=content_app.models.post_file_path),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
