GET http://192.168.1.9:8000/api/v1/group_chats/1/requests/3/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQ3NTQ3OTA5LCJqdGkiOiJlODI4OGY5YzBlNDM0MzlhYjU2YzQ5YzRkMzQxMDQyYyIsInVzZXJfaWQiOjN9.5f9Gl8XYOkQhGU9PCC1UITsB1gf3ns_EmVxF1PDZEqY


