# Generated by Django 3.2.8 on 2022-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatrole',
            old_name='data_joined',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='groupchatrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
