# Generated by Django 3.2.8 on 2022-04-17 10:40

from django.db import migrations, models
import group_chat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat_app', '0003_auto_20220412_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(default='/static/img/me.png', upload_to=group_chat_app.models.group_chat_profile_file_path),
        ),
    ]
