# Generated by Django 3.2.8 on 2022-04-17 20:18

from django.db import migrations, models
import group_chat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat_app', '0004_alter_groupchat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=group_chat_app.models.group_chat_profile_file_path),
        ),
    ]
