export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_CHAT_NOTIFICATIONS = "GET_USER_CHAT_NOTIFICATIONS";
export const ACCEPT_CHAT_NOTIFICATION = "ACCEPT_CHAT_NOTIFICATION";
export const DELETE_CHAT_NOTIFICATION = "DELETE_CHAT_NOTIFICATION";
