# Generated by Django 3.2.7 on 2021-09-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Заголовок', max_length=200)),
                ('text', models.TextField(db_column='Статья')),
                ('created_at', models.DateTimeField(auto_now=True, db_column='Дата создания')),
                ('username', models.CharField(db_column='Пользователь', default=None, max_length=130)),
                ('group', models.CharField(db_column='Группа', default=' ', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='Текст', default=None)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='Дата создания')),
                ('username', models.CharField(db_column='Пользователь', default=None, max_length=130)),
                ('group', models.CharField(db_column='Группа', default=' ', max_length=50, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(db_column='Изображение', default=' ', upload_to='media')),
                ('video', models.FileField(db_column='Видео', default=' ', upload_to='videos')),
                ('file', models.FileField(db_column='Файл', default=' ', upload_to='files')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.post')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
