# Generated by Django 3.2.7 on 2021-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0007_auto_20211004_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(db_column='Аватарка', default='/static/img/me.png', upload_to='media/user_images'),
        ),
    ]
