# Generated by Django 3.2.8 on 2021-11-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен авторизаций.',
                'verbose_name_plural': 'Токены авторизаций.',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже существует.'}, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='acceptauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
