# Generated by Django 3.2.7 on 2021-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0008_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(db_column='Файл', default=' ', upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='photo',
            field=models.ImageField(db_column='Изображение', default=' ', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='video',
            field=models.FileField(db_column='Видео', default=' ', upload_to='media/videos'),
        ),
    ]
