# Generated by Django 3.2.8 on 2021-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0009_auto_20211017_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='soc.Post')),
            ],
        ),
    ]
