# Generated by Django 3.2.8 on 2021-12-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0009_chat_message_personalchat_personalmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
