# Generated by Django 3.2.8 on 2021-10-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
