# Generated by Django 3.2.7 on 2021-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0011_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=' ', upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='photo',
            field=models.ImageField(default=' ', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='video',
            field=models.FileField(default=' ', upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='/static/img/me.png', upload_to='media/user_images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(max_length=30),
        ),
    ]
