# Generated by Django 3.2.8 on 2021-10-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0013_auto_20211023_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
