# Generated by Django 3.2.8 on 2021-12-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0013_groupmessage_polymorphicmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polymorphicmessage',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='polymorphicmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupchatrole',
            name='chat',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='PolymorphicMessage',
        ),
    ]
