# Generated by Django 3.2.8 on 2021-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0015_auto_20211031_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(default=None, upload_to='media/category_images'),
        ),
    ]
