# Generated by Django 3.2.8 on 2021-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0016_remove_groupchat_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrole',
            name='name',
            field=models.CharField(choices=[(1, 'Создатель'), (2, 'Модератор'), (3, 'Участник')], default='Mem', max_length=3),
        ),
    ]
