# Generated by Django 3.2.8 on 2021-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0016_auto_20211101_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(default='', upload_to='media/category_images'),
        ),
    ]
