# Generated by Django 3.2.8 on 2021-12-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0018_alter_groupchatrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrole',
            name='name',
            field=models.CharField(choices=[('Администратор', 'Creator'), ('Модератор', 'Moderator'), ('Участник', 'Member')], default='Участник', max_length=30),
        ),
    ]
