# Generated by Django 3.2.8 on 2021-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(default='/static/img/me.png', upload_to='media/group_avatars'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(help_text='Название чата', max_length=50),
        ),
    ]
