# Generated by Django 3.2.8 on 2021-11-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_alter_personalchat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchat',
            name='users',
        ),
        migrations.AddField(
            model_name='personalchat',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
