# Generated by Django 3.2.8 on 2021-11-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0014_auto_20211104_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
