# Generated by Django 3.2.8 on 2021-11-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_personalchat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='personal_chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.personalchat'),
            preserve_default=False,
        ),
    ]
