# Generated by Django 3.2.8 on 2021-11-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_personalmessage_personal_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalMessage',
        ),
    ]
