# Generated by Django 3.2.8 on 2021-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_personalmessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='token',
            field=models.CharField(default='d4d4adaa-8ac9-45ff-a9b5-fdfd4f5017e7', max_length=36),
        ),
    ]
