# Generated by Django 3.2.8 on 2021-11-09 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_chat_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
