# Generated by Django 3.2.8 on 2021-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
