# Generated by Django 3.2.8 on 2022-01-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
