# Generated by Django 3.2.8 on 2021-12-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('soc', '0014_auto_20211220_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolymorphicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_soc.polymorphicmessage_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='personalmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Личное сообщение', 'verbose_name_plural': 'Личные сообщения'},
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='groupchatrole',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soc.groupchat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalmessage',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soc.personalchat'),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='polymorphicmessage_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soc.polymorphicmessage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('polymorphicmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soc.polymorphicmessage')),
                ('chat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soc.groupchat')),
            ],
            options={
                'verbose_name': 'Групповое сообщение',
                'verbose_name_plural': 'Групповые сообщения',
                'ordering': ('-created_at',),
            },
            bases=('soc.polymorphicmessage',),
        ),
    ]
