export const GET_ALL_CHAT_REQUESTS = "GET_ALL_CHAT_REQUESTS";
export const GET_ALL_CHAT_MEMBERS = "GET_ALL_CHAT_MEMBERS";

export const GET_REQUEST = "GET_REQUEST";
export const CHECK_IS_REQUEST_EXISTS = "CHECK_IS_REQUEST_EXISTS";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";

//-----------------------------------------------------------------------------------------------------------------

export const GET_GROUP_CHAT_LIST = "GET_GROUP_CHAT_LIST";
export const GET_GROUP_CHAT_LIST_WITHOUT_MESSAGES = "GET_GROUP_CHAT_LIST_WITHOUT_MESSAGES";
export const GET_GROUP_CHAT_LIST_WITH_MESSAGES = "GET_GROUP_CHAT_LIST_WITH_MESSAGES";
export const GET_CURRENT_USER_CHAT_LIST = "GET_CURRENT_USER_CHAT_LIST";
export const FILTER_CHAT_LIST_BY_STRING = "FILTER_CHAT_LIST_BY_STRING";
export const CLEAR_FILTERED_CHAT_LIST = "CLEAR_FILTERED_CHAT_LIST"

export const ADD_NEW_GROUP_CHATS_IN_GROUP_CHAT_LIST = "ADD_NEW_GROUP_CHATS_IN_GROUP_CHAT_LIST";
export const FILTER_GROUP_CHAT_LIST_BY_EMPTY_MESSAGES = "FILTER_GROUP_CHAT_LIST_BY_EMPTY_MESSAGES";
export const SORT_GROUP_CHAT_LIST_BY_LAST_MESSAGES = "SORT_GROUP_CHAT_LIST_BY_LAST_MESSAGES";

//-----------------------------------------------------------------------------------------------------------------

export const GET_PERSONAL_CHAT_LIST = "GET_PERSONAL_CHAT_LIST";
export const FILTER_PERSONAL_CHAT_LIST_BY_INTERLOCUTOR_NAME = "FILTER_PERSONAL_CHAT_LIST_BY_INTERLOCUTOR_NAME";

export const ADD_NEW_PERSONAL_CHATS_IN_PERSONAL_CHAT_LIST = "ADD_NEW_PERSONAL_CHATS_IN_PERSONAL_CHAT_LIST";
