export const GET_ALL_CHAT_REQUESTS = "GET_ALL_CHAT_REQUESTS";
export const GET_ALL_CHAT_MEMBERS = "GET_ALL_CHAT_MEMBERS";

export const GET_REQUEST = "GET_REQUEST";
export const CHECK_IS_REQUEST_EXISTS = "CHECK_IS_REQUEST_EXISTS";