# Generated by Django 3.2.8 on 2022-04-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datingprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='city',
            field=models.CharField(default='Moscow', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='name',
            field=models.CharField(default='lol', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='type',
            field=models.CharField(choices=[('TG', 'Telegram'), ('Site', 'Site')], default='Site', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datingprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
