# Generated by Django 3.2.8 on 2022-04-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating_app', '0003_auto_20220418_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedatingprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramdatingprofile',
            name='telegram_id',
            field=models.IntegerField(unique=True),
        ),
    ]
