# Generated by Django 3.2.8 on 2022-04-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0004_auto_20220418_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedatingprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='telegramdatingprofile',
            name='type',
        ),
    ]
