# Generated by Django 3.2.8 on 2022-04-18 20:50

import dating_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_auto_20220418_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedatingprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dating_app.models.dating_profile_file_path),
        ),
        migrations.AlterField(
            model_name='telegramdatingprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dating_app.models.dating_profile_file_path),
        ),
    ]
